### ISSUE TITLE
a simple todo-app

### ISSUE THREAD

**Issue by tamannasgh** [deeqakkk/Journey-with-js#16]
hey @deeqakkk may i add my todo-app here.

**Comment by epicdeepak** [comment]
> hey @deeqakkk may i add my todo-app here.

Create a new issue for the same and go ahead.

**Comment by Vanshika2063** [comment]
please check my pr

**Comment by tamannasgh** [comment]
hey @deeqakkk may you please check and lemme know if that's okay.

added simple todo-app #28
