### ISSUE TITLE
simple clock

### ISSUE THREAD

**Issue by Vanshika2063** [deeqakkk/Journey-with-js#17]
Hey @deeqakkk ,
can i add my clock project in your repository??

**Comment by epicdeepak** [comment]
> Hey @deeqakkk ,
> can i add my clock project in your repository??

Create a new issue for the same and go ahead 🚀💯

**Comment by Vanshika2063** [comment]
new issue or pr?

**Comment by epicdeepak** [comment]
New issue and then a PR.

**Comment by Vanshika2063** [comment]
please check my pr

**Comment by Vanshika2063** [comment]
please check my pr
