### ISSUE TITLE
Want to Add project

### ISSUE THREAD

**Issue by jainpatel25** [deeqakkk/Journey-with-js#19]
random background color

**Comment by epicdeepak** [comment]
Good luck Jain.

**Comment by epicdeepak** [comment]
@jainpatel25 are you still working on this issue? if you need some more time please let me know.
Otherwise, I have to close this issue.

**Comment by jainpatel25** [comment]
Hey, I'm not able to complete my project, I have my college works so can you please close this issue and sorry for that

**Comment by epicdeepak** [comment]
> Hey, I'm not able to complete my project, I have my college works so can you please close this issue and sorry for that

Thank you Jain for the update.
