### ISSUE TITLE
Clock project

### ISSUE THREAD

**Issue by Priyadarshani7** [deeqakkk/Journey-with-js#29]
Making a clock website by using html css and javascript which will show time and date on screen

**Comment by epicdeepak** [comment]
Sure go ahead.

**Comment by harshvardhan614** [comment]
Hi , CAN I add my analog Clock Project in your repository?

**Comment by epicdeepak** [comment]
> Hi , CAN I add my analog Clock Project in your repository?

Surely you can add a project. But we already have a analog clock.
please come again with a new idea.
sorry for the late reply, was stuck in something.
