### ISSUE TITLE
A Weather App

### ISSUE THREAD

**Issue by Uttkarrsh** [deeqakkk/Journey-with-js#4]

**Comment by epicdeepak** [comment]
Yes, you can contribute.
Make a folder 5-Weather-App and put all the files inside it before making a PR.

Note: Next time before opening a issue, make sure you add a proper description.

**Comment by amardeep911** [comment]
Is the issue still persist. Plz assigned this to me

**Comment by Uttkarrsh** [comment]
I have done the changes.

**Comment by Uttkarrsh** [comment]
I have shared the link for project in Readme.me
I am sharing the deployment link here also:-
https://rococo-cat-d54cba.netlify.app/
