### ISSUE TITLE
Animated Tab Bar 

### ISSUE THREAD

**Issue by techseason** [deeqakkk/Journey-with-js#40]
Animated Tab Bar using html css javascript.

**Comment by techseason** [comment]
I want to work on this project please assign me ths issue

**Comment by epicdeepak** [comment]
> I want to work on this project please assign me ths issue

Good luck.

**Comment by techseason** [comment]
I have clicked the unassign me button by mistake can you please reassign me this project.

**Comment by epicdeepak** [comment]
> I have clicked the unassign me button by mistake can you please reassign me this project.

Yeah, assigned again. Please carry on.
