### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by Priyadarshani7** [deeqakkk/Journey-with-js#5]
Building a dice game using html,css and javascript

**Comment by epicdeepak** [comment]
Yes, you can add your project. 
Make a new folder (4-Dice-Game) and put all the files inside it before making a PR.

Good luck.

**Comment by epicdeepak** [comment]
Hi Priya, I will be closing this issue or mark it as available for others in next 48hrs. If you want to some more time to make a PR . Please let me know.
