### ISSUE TITLE
Events page in React with sorting algorithm

### ISSUE THREAD

**Issue by Bhushan8177** [deeqakkk/Journey-with-js#59]

**Comment by Bhushan8177** [comment]
@deeqakkk pls assign it to me!

**Comment by epicdeepak** [comment]
Please write a description for your project.

**Comment by Bhushan8177** [comment]
![image](https://user-images.githubusercontent.com/79825101/196023746-9efd3413-0eb3-488d-839b-f2bbcfc9d21f.png)
all the events can be seen in with ALL button whereas the events in the specific country can be seen by clicking on the country name also the count of the events of can be seen

**Comment by Bhushan8177** [comment]
how should i upload my react project?

**Comment by epicdeepak** [comment]
> how should i upload my react project?

Simply, submit the code. You can also share a live link of your project. 
Sorry for the late reply, was stucked in certain things.

**Comment by Bhushan8177** [comment]
done by my side!!, you can check

**Comment by epicdeepak** [comment]
> done by my side!!, you can check

Just checked and merged it as well. Good Work 👏🏼
