### ISSUE TITLE
Simple Tic-Tac-Toe Game Project

### ISSUE THREAD

**Issue by AcidicArmadillo** [deeqakkk/Journey-with-js#60]
Hello. I want to create a simple tic-tac-toe game with basic HTML,CSS and JS.
Can I add my project?

**Comment by epicdeepak** [comment]
Sure, go ahead.

**Comment by epicdeepak** [comment]
@AcidicArmadillo are you still working on this? if yes please let me know.
otherwise I have to label this as 'open for everyone'.

**Comment by ankitkumar0622** [comment]
Hi @deeqakkk , can you please assign this task to me , I would like to work on this .

**Comment by epicdeepak** [comment]
> Hi @deeqakkk , can you please assign this task to me , I would like to work on this .

Ankit, thank you for your interest but for now no you can't work on this as this issue was opened by @AcidicArmadillo . You can always create a new issue with a new project idea.

**Comment by AcidicArmadillo** [comment]
Hi @deeqakkk . Yes, I'm still working on this project. I was caught up in some personal business for the last couple of days so I wasn't able to make much progress. Nevertheless, I should have it done by tomorrow. Thanks for your consideration.

**Comment by epicdeepak** [comment]
> Hi @deeqakkk . Yes, I'm still working on this project. I was caught up in some personal business for the last couple of days so I wasn't able to make much progress. Nevertheless, I should have it done by tomorrow. Thanks for your consideration.

Thanks for the update, Have merged your PR. Good Work.
