### ISSUE TITLE
Ball Fall game using HTML, CSS and JS

### ISSUE THREAD

**Issue by annupriy** [deeqakkk/Journey-with-js#61]
Hi, I want to create a simple ball fall game with basic HTML, CSS, and JS.
In this game, the Player will have to pass a ball through hurdles and if the ball touches the boundary or it collides with any hurdle then the game will be over and the score of the player will be shown. 
Can I add my project?

**Comment by epicdeepak** [comment]
Sure Annu, Go ahead.
Good luck.
