### ISSUE TITLE
Simple Digital Clock

### ISSUE THREAD

**Issue by Kamlesh72** [deeqakkk/Journey-with-js#68]
I want to add my Digital Clock project here which I made using html, css and Javascript.

**Comment by AnonymousSudh** [comment]
i will make it

**Comment by epicdeepak** [comment]
> i will make it



> I want to add my Digital Clock project here which I made using html, css and Javascript.

@Kamlesh72 are you still working on it? if yes let me know.
Otherwise, I will mark this issue as 'available' for others.

**Comment by epicdeepak** [comment]
> i will make it

Hi @AnonymousSudh for now you can't work on this issue as Kamlesh have created it. You can create a new issue with another idea. Good luck.

**Comment by Kamlesh72** [comment]
Yes, I will complete by 9PM.

**Comment by Kamlesh72** [comment]
#77 Closing this issue as it is successfully completed and merged.
