### ISSUE TITLE
Folder Renaming

### ISSUE THREAD

**Issue by Kamlesh72** [deeqakkk/Journey-with-js#78]
The folders are not renamed properly.
Like after "1 - Background-Changer", there should be "2 - Netflix-Homepage".
Wheras the current scenario is:
1 - Background-Changer
10 - Sunny Summer
11 - Shopping Card

I would like to work on this issue.

**Comment by epicdeepak** [comment]
> The folders are not renamed properly. Like after "1 - Background-Changer", there should be "2 - Netflix-Homepage". Wheras the current scenario is: 1 - Background-Changer 10 - Sunny Summer 11 - Shopping Card
> 
> I would like to work on this issue.

Glad to know that you are looking to contribute, but kamlesh it's not an issues.
If you will open this repo locally, everything is arranged properly. I'm attaching a screenshot for reference.
![image](https://user-images.githubusercontent.com/78724676/197354140-e42b7d29-ed10-4eb7-b1b3-ac330ef2131e.png)

**Comment by Kamlesh72** [comment]
<img width="571" alt="Screenshot 2022-10-22 at 11 11 59 PM" src="https://user-images.githubusercontent.com/90441742/197355147-bedcf390-0605-44ce-b211-94ecd7b62dd3.png">

We can try renaming Github folder like this which will sort them locally as well remotely.

**Comment by Kamlesh72** [comment]
> <img alt="Screenshot 2022-10-22 at 11 11 59 PM" width="571" src="https://user-images.githubusercontent.com/90441742/197355147-bedcf390-0605-44ce-b211-94ecd7b62dd3.png">
> 
> We can try renaming Github folder like this which will sort them locally as well remotely.

https://github.com/Kamlesh72/Journey-with-js/tree/main
